// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC6f_1TfsdC18V6E9VZU46GPttxVnjEe8o',
//     appId: '1:130659922072:web:de81658719a7b0c1cba0ed',
//     messagingSenderId: '130659922072',
//     projectId: 'appdistribution-f59e9',
//     authDomain: 'appdistribution-f59e9.firebaseapp.com',
//     storageBucket: 'appdistribution-f59e9.appspot.com',
//     measurementId: 'G-Z37ZE3VCPM',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBAC64eQzk7UolA9wEiPzRZbChlN_uK67s',
//     appId: '1:130659922072:android:97febe77154ff2f3cba0ed',
//     messagingSenderId: '130659922072',
//     projectId: 'appdistribution-f59e9',
//     storageBucket: 'appdistribution-f59e9.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDJPjH2I9need7jxBNtjiSdpOPib_kaFcQ',
//     appId: '1:130659922072:ios:6c31571378a203edcba0ed',
//     messagingSenderId: '130659922072',
//     projectId: 'appdistribution-f59e9',
//     storageBucket: 'appdistribution-f59e9.appspot.com',
//     iosBundleId: 'com.exampledir.app',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDJPjH2I9need7jxBNtjiSdpOPib_kaFcQ',
//     appId: '1:130659922072:ios:6c31571378a203edcba0ed',
//     messagingSenderId: '130659922072',
//     projectId: 'appdistribution-f59e9',
//     storageBucket: 'appdistribution-f59e9.appspot.com',
//     iosBundleId: 'com.exampledir.app',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyC6f_1TfsdC18V6E9VZU46GPttxVnjEe8o',
//     appId: '1:130659922072:web:da9ad6b802209786cba0ed',
//     messagingSenderId: '130659922072',
//     projectId: 'appdistribution-f59e9',
//     authDomain: 'appdistribution-f59e9.firebaseapp.com',
//     storageBucket: 'appdistribution-f59e9.appspot.com',
//     measurementId: 'G-VJNJTSPCTR',
//   );
// }
