platform :ios, '13.0'
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  flutter_install_all_packages File.dirname(__FILE)
  pod 'Firebase/Core', '~> 10.27.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
     end
    end
   end
